# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 390a42d8e17e5868837ceb05e332acb357bdc2d7f94e3c5af4b9c3fba6795f97896a8e863cdf721d6efb767472c77426ac6cf906e5a47eedc3ff6e4f0f9a9856

test:
  secret_key_base: dae569b46035b899e6f305d42539dc338aed4891eac68e00d5a663e3e92869ee782bf5764460ab36416e4f5d2bc947fdb5eb999ef026de412d31dc38d04ab653

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
