# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3177783d685a9397caa8483ec9d15556e31fb1a82460991297d768f261b6331f7591aa4e6c060797bb44e1b30c20b4ce0f22ba7b137bd717ad0e2172b7771595

test:
  secret_key_base: 91cc43e8fe227256ba2a9a7ddf1e1efefa786da833824795f742661343d41aaade45079c4f62016c30998fcac24b7c404470ae1726b6c7a283f5a4c19210f13d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
