# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22c03e8711dad3be3daa2b7b75febe0ea579907048debc2c9606b0c2896280ff748e9af94b28ef55aba4806e9c71b0c8170869b963558deddbd6c17a6b4781f3

test:
  secret_key_base: b6cf7dabba0e6fa1b3069b4f3b7c41d8234be60ef7cbf5437828b08c18936d535bea66ec18138e06c529cea0a5ddaa1223f2ef44d84d97574266c0ffd687b082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
